<?php
/**
 * @file
 * Code for the ContactsID App feature.
 */

//include_once 'contactsid_app.forms.inc';

/**
 * Implements hook_page_alter().
 */
function contactsid_app_page_alter(&$page) {
  // Include the ContactsID app if the user is authorized and not on an admin
  // page.
  if (user_access('access contactsid app') && !path_is_admin(current_path())) {
    contactsid_app_page_include($page);
  }
}

/**
 * Implements hook_permission().
 */
function contactsid_app_permission() {
  return array(
    'access contactsid app' => array(
      'title' => t('Access Contacts ID app'),
      'description' => t('Access the Contacts ID app'),
    ),
  );
}

/**
 * Helper function to add all client-side resources for the app.
 */
function contactsid_app_page_include(&$page) {
  $path = drupal_get_path('module', 'contactsid_app');

  // Include JS dependencies
  drupal_add_js($path . '/libraries/angular/angular.min.js');
  drupal_add_js($path . '/libraries/angular-route/angular-route.min.js');
  drupal_add_js($path . '/libraries/angular-busy/angular-busy.js');
  drupal_add_js($path . '/libraries/angular-spinkit/build/angular-spinkit.min.js');

  // Include CSS dependencies
  drupal_add_css($path . '/libraries/angular-busy/angular-busy.css');
  drupal_add_css($path . '/libraries/angular-spinkit/build/angular-spinkit.min.css');


  // Embed div elements for the ng app.
  $page['page_bottom'][] = array(
    '#type' => 'markup',
    '#markup' => '<div id="contactsid-app-view-wrapper" class="hide"><div id="contactsid-app" class="contactsid-app container"><div id="contactsid-app-view" class="" ng-view></div><div class=""><route-loading-indicator></route-loading-indicator></div></div></div>',
  );

  // Add Drupal JS settings.
  $app_data = array('contactsId' => array(
    'logoutPath' => '/user/logout',
    'appSourcePath' => base_path() . $path,
  ));
  drupal_add_js($app_data, 'setting');

  // Include the app's CSS and JS files.
  drupal_add_js($path . '/js/app.js', array('preprocess' => FALSE));
  drupal_add_css($path . '/css/app.css', array('preprocess' => FALSE));
}
